name: shellcheck

on:
  push:
    paths:
      - 'scripts/**'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
      - 'scripts/**'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'
